# This is a basic workflow that is manually triggered

name: vm_size

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    # inputs: None?

jobs:
  vm_size:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Calculate diff
      run: |
        echo "Getting file from storage..."
        curl https://tflintrulesstore.z5.web.core.windows.net/vm-size.json --output rules/.tflint-azure-config/vm-size.json
        echo "Done."
        echo "Calculating diff..."
        git diff
        echo "Done."

